### Obtener mediciones
GET http://localhost:8081/rest/getmediciones.php

### Enviar Medicion
POST http://localhost:8081/rest/enviarMedicion.php
Content-Type: application/json

{
  "Hora": "22:00",
  "Dia": "2024-10-05",
  "Lugar": "Estacion Norte",
  "TipoGas": "CO2",
  "Valor": 45
}
